/*
 * RSOC Answer Engine — localized, region-aware backend.
 * Content (hooks + openers) is generated by the multilingual model per
 * (region, vertical, locale) and cached in Upstash so it's instant after the
 * first view. DEMO ONLY: advertisers/content are AI-generated and synthetic,
 * not legally-vetted ad inventory.
 */

/* ---------------- markets (by language) / verticals ----------------
 * Each market is one language/locale with culturally-appropriate verticals.
 * `people` is the nationality adjective injected into AI image prompts so the
 * Facebook creative matches the audience (e.g. a Japanese family for ja). */
export const REGIONS = {
  en_us: {
    label: 'English (US)', dir: 'ltr', currency: 'USD', people: 'American',
    locales: [{ code: 'en-US', name: 'English' }],
    verticals: {
      medicare: { label: 'Medicare', color: '#1877f2', photo: 'medicare',
        brief: '2026 US Medicare Advantage plans for seniors: $0-premium plans, dental/vision/hearing, grocery/OTC cards, Part B giveback, drug plans, enrollment windows. Advertisers like Humana, Aetna, UnitedHealthcare.',
        disclaimer: 'Not connected with or endorsed by the U.S. government or the federal Medicare program. Benefits vary by plan and area.' },
      roofing: { label: 'Roofing', color: '#e8590c', photo: 'roofing',
        brief: 'US residential roof replacement in 2026: cost, free inspections, financing, storm/insurance claims, metal vs shingle. Advertisers like Modernize, Angi, Erie Metal Roofs.',
        disclaimer: 'Quotes are provided by independent local contractors. Pricing and availability vary by area.' },
      debt: { label: 'Debt Relief', color: '#2b8a3e', photo: 'debt',
        brief: 'US unsecured debt relief: settlement vs consolidation, no upfront fees, credit impact, eligibility, timelines. Advertisers like National Debt Relief, Freedom Debt Relief, Achieve.',
        disclaimer: 'Debt relief programs are not available in all states; results vary; enrollment may affect credit. Not legal or financial advice.' }
    }
  },
  en_gb: {
    label: 'English (UK)', dir: 'ltr', currency: 'GBP', people: 'British',
    locales: [{ code: 'en-GB', name: 'British English' }],
    verticals: {
      energy: { label: 'Boiler & Insulation Grants', color: '#1971c2', photo: 'solar',
        brief: 'UK home-energy upgrades for homeowners in 2026: government grants for boilers, insulation and heat pumps, lower energy bills, eligibility check, free home survey. Synthetic UK installer advertisers.',
        disclaimer: 'Grant eligibility depends on property and circumstances. Quotes from independent installers. Demo content.' },
      carins: { label: 'Car Insurance', color: '#4263eb', photo: 'insurance',
        brief: 'UK car insurance comparison: switch and save, compare quotes from top insurers in minutes, multi-car and black-box options, free quote. Synthetic comparison-site advertisers.',
        disclaimer: 'Savings vary by driver profile and vehicle. Demo content.' },
      life50: { label: 'Over-50s Life Cover', color: '#5f3dc4', photo: 'life',
        brief: 'UK over-50s guaranteed life insurance and funeral plans: fixed monthly premiums, no medical needed, cash lump sum for loved ones, optional gift on joining. Synthetic insurer advertisers.',
        disclaimer: 'Over time premiums may exceed the payout; terms apply. Demo content.' }
    }
  },
  fr: {
    label: 'Français', dir: 'ltr', currency: 'EUR', people: 'French',
    locales: [{ code: 'fr-FR', name: 'French' }],
    verticals: {
      solaire: { label: 'Panneaux Solaires', color: '#f59f00', photo: 'solar',
        brief: 'Residential solar panels for French homeowners: cut the electricity bill, government aid (MaPrimeRénov/prime autoconsommation), financing, free home assessment. Synthetic French installer advertisers.',
        disclaimer: 'Savings and aid depend on the home and consumption. Quotes from independent installers. Demo content.' },
      ve: { label: 'Voiture Électrique', color: '#0ca678', photo: 'ev',
        brief: 'Electric-vehicle leasing (LOA/LLD) for France: low monthly payment, government bonus/social leasing, all-inclusive offers, instant quote. Synthetic leasing advertisers.',
        disclaimer: 'Offers subject to status and eligibility. Demo content.' },
      mutuelle: { label: 'Mutuelle Santé', color: '#1098ad', photo: 'health',
        brief: 'Top-up health insurance (mutuelle) for France: compare plans, senior and family cover, better reimbursement, free quote in minutes. Synthetic mutuelle advertisers.',
        disclaimer: 'Cover and price vary by profile. Demo content.' }
    }
  },
  de: {
    label: 'Deutsch', dir: 'ltr', currency: 'EUR', people: 'German',
    locales: [{ code: 'de-DE', name: 'German' }],
    verticals: {
      solar: { label: 'Solar & Wärmepumpe', color: '#f59f00', photo: 'solar',
        brief: 'Solar panels and heat pumps for German homeowners: lower energy bills, government subsidies (KfW/BAFA), financing, free home assessment. Synthetic German installer advertisers.',
        disclaimer: 'Savings and subsidy eligibility vary by household. Quotes from independent installers. Demo content.' },
      eauto: { label: 'E-Auto Leasing', color: '#0ca678', photo: 'ev',
        brief: 'Electric-vehicle leasing for Germany: low monthly lease, all-inclusive deals, instant quote, business and private options. Synthetic leasing advertisers.',
        disclaimer: 'Offers subject to status. Demo content.' },
      versicherung: { label: 'Versicherungen', color: '#4263eb', photo: 'insurance',
        brief: 'Home and car insurance comparison for Germany: switch and save, compare top insurers in minutes, free quote. Synthetic comparison-site advertisers.',
        disclaimer: 'Savings vary by profile. Demo content.' }
    }
  },
  ja: {
    label: '日本語', dir: 'ltr', currency: 'JPY', people: 'Japanese',
    locales: [{ code: 'ja-JP', name: 'Japanese' }],
    verticals: {
      seimei: { label: '生命保険 (Life)', color: '#5f3dc4', photo: 'life',
        brief: 'Life and medical insurance for families in Japan: affordable cover, compare plans, instant online quote, coverage for medical and cancer. Synthetic insurer advertisers.',
        disclaimer: 'Cover and terms vary by plan. Demo content.' },
      eikaiwa: { label: '英会話 (English)', color: '#1c7ed6', photo: 'ingles',
        brief: 'Online English conversation lessons (eikaiwa) for adults in Japan: speak confidently, native and bilingual tutors, free trial lesson, flexible schedule. Synthetic ed-tech advertisers.',
        disclaimer: 'Results vary by effort and plan. Demo content.' },
      ryoko: { label: '旅行 (Travel)', color: '#0c8599', photo: 'travel',
        brief: 'Discounted travel, flight and hotel deals for travellers from Japan: limited-time fares, bundle and save, flexible booking. Synthetic OTA advertisers.',
        disclaimer: 'Prices and availability change. Demo content.' }
    }
  },
  hi: {
    label: 'हिन्दी', dir: 'ltr', currency: 'INR', people: 'Indian',
    locales: [{ code: 'hi-IN', name: 'Hindi' }],
    verticals: {
      jeevan: { label: 'जीवन बीमा (Life)', color: '#5f3dc4', photo: 'life',
        brief: 'Term and life insurance for families in India: high cover for a low premium, compare plans, instant online quote, tax benefits under 80C. Synthetic insurer advertisers.',
        disclaimer: 'Cover and tax treatment vary by plan and law. Demo content.' },
      tuition: { label: 'ट्यूशन (Tutoring)', color: '#1c7ed6', photo: 'tutoring',
        brief: 'Online tutoring and exam prep (JEE/NEET/board) for students in India: expert tutors, top scores, free demo class, flexible batches. Synthetic ed-tech advertisers.',
        disclaimer: 'Results vary by student. Demo content.' },
      loan: { label: 'पर्सनल लोन (Loan)', color: '#1971c2', photo: 'debt',
        brief: 'Personal loans for consumers in India: quick approval, low EMI, minimal documents, instant eligibility check. Synthetic lender advertisers.',
        disclaimer: 'Subject to credit approval; terms vary by lender. Not financial advice. Demo content.' }
    }
  },
  es: {
    label: 'Español', dir: 'ltr', currency: 'EUR', people: 'Spanish',
    locales: [{ code: 'es-ES', name: 'Spanish' }],
    verticals: {
      solar: { label: 'Energía Solar', color: '#f59f00', photo: 'solar',
        brief: 'Residential solar panels for homeowners in Spain: cut the electricity bill, subsidies and IBI rebates, financing, free assessment. Synthetic installer advertisers.',
        disclaimer: 'Savings and subsidies depend on the home and consumption. Quotes from independent installers. Demo content.' },
      seguro: { label: 'Seguros', color: '#4263eb', photo: 'insurance',
        brief: 'Home and car insurance comparison for Spain: switch and save, compare top insurers in minutes, free quote. Synthetic comparison-site advertisers.',
        disclaimer: 'Savings vary by profile. Demo content.' },
      ingles: { label: 'Cursos de Inglés', color: '#7048e8', photo: 'ingles',
        brief: 'Online English courses for adults in Spain: advance your career, conversational fluency, free trial lesson, flexible plans. Synthetic ed-tech advertisers.',
        disclaimer: 'Results vary by effort and plan. Demo content.' }
    }
  }
};

function localeName(region, locale) {
  const r = REGIONS[region]; if (!r) return 'English';
  const l = (r.locales || []).find(x => x.code === locale);
  return l ? l.name : (r.locales[0] ? r.locales[0].name : 'English');
}
function vertical(region, vkey) {
  const r = REGIONS[region]; if (!r) return null;
  return r.verticals[vkey] || null;
}

/* ---------------- model callers ---------------- */
async function callClaude(system, userText, history) {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) throw new Error('Missing ANTHROPIC_API_KEY');
  const model = process.env.CLAUDE_MODEL || 'claude-sonnet-4-6';
  const messages = [];
  for (const h of history || []) messages.push({ role: h.role, content: h.content });
  messages.push({ role: 'user', content: userText });
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01' },
    body: JSON.stringify({ model, max_tokens: 1500, system, messages })
  });
  if (!res.ok) throw new Error(`Anthropic ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return (data.content || []).map(b => b.text || '').join('');
}
async function callGemini(system, userText, history) {
  const key = process.env.GEMINI_API_KEY;
  if (!key) throw new Error('Missing GEMINI_API_KEY');
  const model = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
  const contents = [];
  for (const h of history || []) contents.push({ role: h.role === 'assistant' ? 'model' : 'user', parts: [{ text: h.content }] });
  contents.push({ role: 'user', parts: [{ text: userText }] });
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`;
  const res = await fetch(url, {
    method: 'POST', headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ systemInstruction: { parts: [{ text: system }] }, contents, generationConfig: { temperature: 0.8, responseMimeType: 'application/json' } })
  });
  if (!res.ok) throw new Error(`Gemini ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const parts = data?.candidates?.[0]?.content?.parts || [];
  return parts.map(p => p.text || '').join('');
}
async function callLLM(system, userText, history) {
  const provider = (process.env.PROVIDER || 'claude').toLowerCase();
  return provider === 'gemini' ? callGemini(system, userText, history) : callClaude(system, userText, history);
}
function parseJSON(raw) {
  if (!raw) throw new Error('Empty model response');
  let s = raw.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '');
  const a = s.search(/[\[{]/); const b = Math.max(s.lastIndexOf(']'), s.lastIndexOf('}'));
  if (a !== -1 && b !== -1) s = s.slice(a, b + 1);
  return JSON.parse(s);
}

/* ---------------- prompts ---------------- */
function hooksPrompt(v, lang, disclaimer) {
  return `You write scroll-stopping Facebook posts for a content page (a helpful guide/hub we own). They must feel like genuinely INTERESTING, native posts a real person stops to read — NOT obvious ads. DEMO use.
Vertical: ${v.brief}
Write EVERYTHING in ${lang}.

GOAL: make a real person STOP scrolling and feel curious, surprised, or something real. The best Facebook creative is a hook, not a sales pitch. Each "hook" is ONE short line (~6–14 words). Win with angles like: a surprising fact or number, a relatable everyday moment, a curiosity gap ("Most people over 50 don't realise this…"), a question that makes you think, a gentle myth-bust, light social proof ("Thousands quietly switched in 2026"), a "nobody tells you…" insight.

BANNED — this copy reads as a cheap ad and kills engagement, NEVER use it as the hook: "Get a free quote today", "Sign up now", "Click here", "Limited time offer", "Call now", "Act fast", "Apply today", or any generic call-to-action-as-headline. The call-to-action belongs ONLY on the button (cta), never in the hook. No disclaimers, brand names, or legal hedges in the hook. Stay honest (no false guarantees) but lead with intrigue and value, not selling.

Produce 10 DISTINCT hooks, each a clearly different compelling angle: surprising stat, relatable story opener, curiosity gap, provocative question, myth-bust, social proof, a "nobody tells you…" insight, a number/price reveal, a what-if, a did-you-know. They must read like posts people would actually engage with — if one sounds like an ad, rewrite it.

WHOSE AD THIS IS: This Facebook ad is run by OUR OWN content page for this topic (a helpful guide / comparison hub we own), NOT by any insurer, lender or advertiser. Do NOT use a real company/brand (no Humana, Aetna, GEICO, LIC, etc.) as the page. Invent ONE neutral, trustworthy, ownable content-brand page name fitting ${lang} and this vertical (a "guide", "hub", "finder" vibe) and use that SAME page name in "adv" for ALL 10. Put OUR OWN content-site domain in "url" for all 10 — never a real advertiser's domain. Real advertisers appear only later, inside the chat.

Return STRICT JSON: an array of exactly 10 objects (all sharing the same "adv" page name and "url" domain), each:
{"hook":"ONE short clicky line, <=14 words, no disclaimer, in ${lang}","head":"image-overlay headline (in ${lang}, <=5 words)","adv":"our content page name (same for all 10)","url":"www.our-content-site.com","cta":"button text (in ${lang}, 2-3 words)"}
Output only the JSON array.`;
}
function openerPrompt(v, lang, disclaimer, full) {
  const lengthLine = full
    ? `Give a helpful FIRST answer in ${lang} that fits on ONE phone screen with no scrolling — about 4-6 sentences, roughly 600-850 characters MAX (never longer). Pack in the key facts, real numbers/ranges, and the main things to watch out for, like the smartest, most helpful friend they have. Tight and genuinely useful — no fluff, no padding, no salesy tone.`
    : `Answer in ${lang} in 2-4 tight, high-value sentences (no fluff, no salesy tone) — like the smartest, most helpful friend they have, with concrete facts and the key things to know.`;
  const kwLine = full
    ? `INLINE HIGH-VALUE KEYWORDS: this first answer is our prime monetization surface, so naturally weave in and mark AT LEAST 3 (3-4 ideal) genuinely relevant, high-CPC commercial keywords. Use EXACTLY this syntax, ALWAYS with both an id and the visible phrase separated by a pipe: [[id|the exact visible phrase in ${lang}]] where id is a short lowercase ascii slug — e.g. [[roof_cost|roof replacement cost]]. NEVER write a marker without the "id|" part (never [[phrase]] alone). Include at least 3 distinct marked phrases — the most valuable buyer phrases for THIS question. They must read naturally, never forced or spammy.`
    : `INLINE KEYWORDS — sparingly: wrap at most 1-2 genuinely high-CPC, high-buyer-intent phrases as [[id|the exact visible phrase in ${lang}]] (id = short lowercase ascii slug). Mark only truly high-value buyer terms; zero is fine — never force one.`;
  return `You are a genuinely helpful expert assistant whose #1 priority is to actually help the person. ${lengthLine}
Topic: ${v.brief}

CRITICAL: Just answer the question directly. NEVER mention "the ad", "this ad", "the Facebook ad", that the person clicked anything, or describe/react to an ad. Respond as if the person simply asked you the question themselves.

${kwLine}
High-value keyword examples by category (Google Ads / SEMrush CPC): legal ("car accident lawyer", "mesothelioma claim"), insurance ("auto insurance quote", "buy life insurance", "Medicare Advantage plans", "compare car insurance"), finance ("debt relief program", "refinance rates", "personal loan"), home/solar ("solar panel installation", "roof replacement quote"), health ("private health insurance"). NEVER mark generic, informational, or low-value words. Each marked phrase must read naturally in the sentence.
For each id used, give one realistic, compelling sponsored ad.

ENGAGING FOLLOW-UPS (these become tappable buttons that load a NEW answer, like ChatGPT's suggested next questions): provide 4-6 follow-up questions in ${lang} a curious person would genuinely want to tap next — specific, tempting, natural next steps that pull them deeper toward comparing/choosing/qualifying. Never generic filler.

Include a soft honest disclaimer where relevant (${disclaimer}).

ADVERTISER REALISM: Use a REAL, well-known advertiser that genuinely operates in this market and vertical, and put its REAL public website in both "disp" and "url" (absolute https, e.g. https://www.humana.com). Do NOT invent fake domains or fake brands. The advertiser name, headline and copy must read like that brand's own ad, localized to ${lang}.

Return STRICT JSON only:
{"answer":"... in ${lang} with [[id|phrase]] markers","ads":{"<id>":{"adv":"Real brand name","disp":"www.realbrand.com","url":"https://www.realbrand.com","head":"","desc":"","cta":"","sitelinks":["",""]}},"suggest":["",""]}
Output only the JSON object.`;
}

/* ---------------- general homepage assistant (ChatGPT-style, topic-agnostic) ---------------- */
function localeLang(locale) {
  const c = String(locale || 'en').toLowerCase();
  if (c.startsWith('fr')) return 'French';
  if (c.startsWith('de')) return 'German';
  if (c.startsWith('ja')) return 'Japanese';
  if (c.startsWith('hi')) return 'Hindi';
  if (c.startsWith('es')) return 'Spanish';
  return 'English';
}
function generalChatPrompt(lang) {
  return `You are Questions Answer, a friendly, highly knowledgeable AI assistant. Answer the user's question genuinely, clearly and usefully in ${lang} — accuracy and real helpfulness come FIRST, like the best of ChatGPT. Keep it focused: a few short paragraphs; use a short list only when it genuinely helps.

ONLY when the question has real commercial/buyer intent (insurance, loans, mortgages, solar, legal help, medical plans, home services, travel deals, etc.), naturally mark 1-3 of the highest-value commercial keywords using EXACTLY this syntax, ALWAYS with an id and the visible phrase separated by a pipe: [[id|the exact visible phrase in ${lang}]] where id is a short lowercase ascii slug. NEVER write a marker without the "id|" part. These become sponsored results. Prefer high-CPC buyer phrases (legal, insurance, finance, solar, health). If the question is informational or non-commercial, mark ZERO — never force a keyword.
For each marked id, provide one realistic sponsored ad from a REAL, well-known advertiser with its REAL https homepage in "url" and "disp".
Also give 3-5 natural follow-up questions the user might want to ask next.

Return STRICT JSON only:
{"answer":"your helpful answer in ${lang}, with optional [[id|phrase]] markers","ads":{"<id>":{"adv":"Real brand","disp":"www.brand.com","url":"https://www.brand.com","head":"","desc":"","cta":"","sitelinks":["",""]}},"suggest":["question 1","question 2"]}
Output only the JSON object.`;
}

/* ---------------- Upstash (cache + counters + leads) ---------------- */
const MIN_COUNT = 3, MAX_SET = 200;
function redisUrl() { return process.env.KV_REST_API_URL || process.env.UPSTASH_REDIS_REST_URL || ''; }
function redisToken() { return process.env.KV_REST_API_TOKEN || process.env.UPSTASH_REDIS_REST_TOKEN || ''; }
function redisOn() { return !!(redisUrl() && redisToken()); }
async function redis(cmd) {
  const url = redisUrl(), token = redisToken(); if (!url || !token) return null;
  const res = await fetch(url, { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: JSON.stringify(cmd) });
  if (!res.ok) throw new Error('redis ' + res.status);
  return (await res.json()).result;
}
async function cacheGet(key) { try { if (!redisOn()) return null; const v = await redis(['GET', key]); return v ? JSON.parse(v) : null; } catch { return null; } }
async function cacheSet(key, val) { try { if (redisOn()) await redis(['SET', key, JSON.stringify(val)]); } catch {} }
function hashStr(s) { let h = 0; s = String(s); for (let i = 0; i < s.length; i++) { h = (h * 31 + s.charCodeAt(i)) | 0; } return (h >>> 0).toString(36); }

/* ---------------- generation (cached) ---------------- */
const CACHE_VER = 'v10';   // bump to invalidate cached hooks/openers after a prompt change
export async function getLineup(region, vkey, locale) {
  const v = vertical(region, vkey); if (!v) throw new Error('Unknown vertical');
  const lang = localeName(region, locale);
  const key = `hooks:${CACHE_VER}:${locale}:${region}:${vkey}`;
  const cached = await cacheGet(key); if (cached) return cached;
  const raw = await callLLM(hooksPrompt(v, lang, v.disclaimer), 'Generate the 10 hooks now.');
  let arr = parseJSON(raw); if (!Array.isArray(arr)) arr = arr.hooks || [];
  arr = arr.filter(x => x && x.hook).slice(0, 10).map((x, i) => ({ id: 'v' + (i + 1), hook: String(x.hook), head: String(x.head || x.hook).slice(0, 60), adv: String(x.adv || 'Sponsored'), url: String(x.url || 'www.example.com'), cta: String(x.cta || 'Learn More') }));
  if (arr.length) await cacheSet(key, arr);
  return arr;
}
export async function getOpener(region, vkey, locale, hook) {
  const v = vertical(region, vkey); if (!v) throw new Error('Unknown vertical');
  const lang = localeName(region, locale);
  const key = `opener:${CACHE_VER}:${locale}:${region}:${vkey}:${hashStr(hook)}`;
  const cached = await cacheGet(key); if (cached) return cached;
  const raw = await callLLM(openerPrompt(v, lang, v.disclaimer, true), `A visitor just arrived with this on their mind: "${hook}". Give your thorough, screen-filling first answer to what they want to know, accounting for any "$0"/free/price detail in it, and naturally include at least 3 high-value keyword phrases. Do NOT mention an ad or that they clicked anything — just answer the question itself.`);
  const out = normalizeReply(parseJSON(raw));
  await cacheSet(key, out);
  return out;
}

function normalizeReply(obj) {
  if (typeof obj.answer !== 'string') throw new Error('No answer');
  // repair markers the model wrote without an id, e.g. [[phrase]] -> [[slug|phrase]], so they always highlight
  obj.answer = obj.answer.replace(/\[\[([^\]|]+)\]\]/g, (m, phrase) => {
    const slug = String(phrase).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').slice(0, 24) || 'kw';
    return `[[${slug}|${String(phrase).trim()}]]`;
  });
  obj.ads = obj.ads && typeof obj.ads === 'object' ? obj.ads : {};
  obj.suggest = Array.isArray(obj.suggest) ? obj.suggest : [];
  return obj;
}

/* ---------------- follow-up chat (localized) ---------------- */
function canonical(s) { s = String(s || '').toLowerCase().replace(/\s+/g, ' ').trim().replace(/[.?!]+$/, ''); return s ? s[0].toUpperCase() + s.slice(1) : s; }
const BANNED = /\b(fuck|shit|bitch|cunt|nigger|faggot|kill yourself|kys)\b/i;
function isLoggable(s) { return s.length >= 8 && s.length <= 120 && /[\p{L}]/u.test(s) && !/[\w.+-]+@[\w-]+\.[a-z]{2,}/i.test(s) && !/(?:\+?\d[\s().-]?){7,}/.test(s) && !/\b\d{5,}\b/.test(s) && !BANNED.test(s); }

async function logQuestion(scope, q) {
  try { if (!redisOn()) return; const c = canonical(q); if (!isLoggable(c)) return; const key = `paa:${scope}`; await redis(['ZINCRBY', key, '1', c]); await redis(['ZREMRANGEBYRANK', key, '0', String(-(MAX_SET + 1))]); } catch {}
}
async function blendSuggestions(scope, currentQ, modelSuggest) {
  const cq = canonical(currentQ); const model = (modelSuggest || []).filter(Boolean).slice(0, 3); const seen = new Set(model.map(canonical)); seen.add(cq); const popular = [];
  try { if (redisOn()) { const raw = await redis(['ZREVRANGE', `paa:${scope}`, '0', '11', 'WITHSCORES']); if (Array.isArray(raw)) { for (let i = 0; i < raw.length; i += 2) { const m = raw[i], sc = Number(raw[i + 1]); const c = canonical(m); if (sc >= MIN_COUNT && !seen.has(c)) { seen.add(c); popular.push(m); } if (popular.length >= 3) break; } } } } catch {}
  const blended = [...model, ...popular].slice(0, 6); return blended.length ? blended : (modelSuggest || []);
}

export async function ask(region, vkey, locale, question, history) {
  const v = vertical(region, vkey); if (!v) throw new Error('Unknown vertical');
  const lang = localeName(region, locale);
  const raw = await callLLM(openerPrompt(v, lang, v.disclaimer, false), question, history);
  const out = normalizeReply(parseJSON(raw));
  const scope = `${locale}:${region}:${vkey}`;
  await logQuestion(scope, question);
  out.suggest = await blendSuggestions(scope, question, out.suggest);
  return out;
}

export async function chat(question, history, locale) {
  const lang = localeLang(locale);
  const raw = await callLLM(generalChatPrompt(lang), question, history);
  const out = normalizeReply(parseJSON(raw));
  const scope = `home:${String(locale || 'en').replace(/[^a-z0-9-]/gi, '').slice(0, 12)}`;
  await logQuestion(scope, question);
  out.suggest = await blendSuggestions(scope, question, out.suggest);
  return out;
}

/* ---------------- public metadata for the UI ---------------- */
export function publicRegions() {
  const out = {};
  for (const [rk, r] of Object.entries(REGIONS)) {
    out[rk] = { label: r.label, dir: r.dir, currency: r.currency, people: r.people, locales: r.locales,
      verticals: Object.fromEntries(Object.entries(r.verticals).map(([vk, v]) => [vk, { label: v.label, color: v.color, photo: v.photo, disclaimer: v.disclaimer }])) };
  }
  return out;
}

/* ---------------- leads + events ---------------- */
function validEmail(raw) { const e = String(raw || '').trim().toLowerCase(); return e.length <= 120 && /^[^\s@]+@[^\s@]+\.[a-z]{2,}$/.test(e) ? e : null; }
export async function storeLead(scope, email) {
  const e = validEmail(email); if (!e) throw new Error('Please enter a valid email address.');
  const k = String(scope || 'all').replace(/[^a-z0-9:_-]/gi, '').slice(0, 60);
  if (redisOn()) { try { await redis(['SADD', `leads:${k}`, e]); await redis(['SADD', 'leads:all', e]); await redis(['HINCRBY', `stats:${k}`, 'email_optin', '1']); } catch {} }
  return { ok: true };
}
export async function track(scope, metric) {
  try { const k = String(scope || 'all').replace(/[^a-z0-9:_-]/gi, '').slice(0, 60); const m = String(metric || ''); if (redisOn() && /^[a-z0-9:_-]{1,40}$/i.test(m)) await redis(['HINCRBY', `stats:${k}`, m, '1']); } catch {}
  return { ok: true };
}

// map the visitor's country (Vercel geo header) to a default region + locale
function geoDefault(req) {
  const cc = String((req.headers && (req.headers['x-vercel-ip-country'] || req.headers['x-country'])) || '').toUpperCase();
  const M = {
    US:['en_us','en-US'], CA:['en_us','en-US'],
    GB:['en_gb','en-GB'], IE:['en_gb','en-GB'], AU:['en_gb','en-GB'], NZ:['en_gb','en-GB'], SG:['en_gb','en-GB'], ZA:['en_gb','en-GB'],
    FR:['fr','fr-FR'], BE:['fr','fr-FR'], LU:['fr','fr-FR'],
    DE:['de','de-DE'], AT:['de','de-DE'], CH:['de','de-DE'],
    JP:['ja','ja-JP'],
    IN:['hi','hi-IN'],
    ES:['es','es-ES'], MX:['es','es-ES'], AR:['es','es-ES'], CL:['es','es-ES'], CO:['es','es-ES'], PE:['es','es-ES'], UY:['es','es-ES'], EC:['es','es-ES'], VE:['es','es-ES']
  };
  const m = M[cc] || ['en_us', 'en-US'];
  return { country: cc || null, region: m[0], locale: m[1] };
}

export default async function handler(req, res) {
  if (req.method === 'GET') {
    // allow a quick GET for the regions metadata (handy + cacheable)
    if ((req.url || '').includes('/api/ask')) { res.status(200).json({ regions: publicRegions(), detected: geoDefault(req) }); return; }
  }
  if (req.method !== 'POST') { res.status(405).json({ error: 'Method not allowed' }); return; }
  try {
    let body = req.body;
    if (typeof body === 'string') body = JSON.parse(body || '{}');
    if (!body || typeof body !== 'object') body = {};
    const action = body.action || 'ask';
    const { region, vertical, locale, hook, question, history, email, metric, scope } = body;

    if (action === 'regions') { res.status(200).json({ regions: publicRegions(), detected: geoDefault(req) }); return; }
    if (action === 'lineup') {
      if (!region || !vertical || !locale) { res.status(400).json({ error: 'region, vertical, locale required' }); return; }
      res.status(200).json({ variants: await getLineup(region, vertical, locale) }); return;
    }
    if (action === 'opener') {
      if (!region || !vertical || !locale || !hook) { res.status(400).json({ error: 'region, vertical, locale, hook required' }); return; }
      res.status(200).json(await getOpener(region, vertical, locale, String(hook).slice(0, 300))); return;
    }
    if (action === 'chat') {
      if (!question) { res.status(400).json({ error: 'question required' }); return; }
      const loc = locale || geoDefault(req).locale;
      res.status(200).json(await chat(String(question).slice(0, 1000), history, loc)); return;
    }
    if (action === 'lead') { res.status(200).json(await storeLead(scope, email)); return; }
    if (action === 'event') { res.status(200).json(await track(scope, metric)); return; }

    // default: localized follow-up chat
    if (!region || !vertical || !locale || !question) { res.status(400).json({ error: 'region, vertical, locale, question required' }); return; }
    res.status(200).json(await ask(region, vertical, locale, String(question).slice(0, 500), history));
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
}
