/*
 * RSOC Answer Engine — localized, region-aware backend.
 * Content (hooks + openers) is generated by the multilingual model per
 * (region, vertical, locale) and cached in Upstash so it's instant after the
 * first view. DEMO ONLY: advertisers/content are AI-generated and synthetic,
 * not legally-vetted ad inventory.
 */

/* ---------------- regions / verticals / locales ---------------- */
export const REGIONS = {
  america: {
    label: 'Americas (US)', dir: 'ltr', currency: 'USD',
    locales: [{ code: 'en-US', name: 'English' }, { code: 'es-US', name: 'US Spanish' }],
    verticals: {
      medicare: { label: 'Medicare', color: '#1877f2',
        brief: '2026 US Medicare Advantage plans for seniors: $0-premium plans, dental/vision/hearing, grocery/OTC cards, Part B giveback, drug plans, enrollment windows. Advertisers like Humana, Aetna, UnitedHealthcare.',
        disclaimer: 'Not connected with or endorsed by the U.S. government or the federal Medicare program. Benefits vary by plan and area.' },
      roofing: { label: 'Roofing', color: '#e8590c',
        brief: 'US residential roof replacement in 2026: cost, free inspections, financing, storm/insurance claims, metal vs shingle. Advertisers like Modernize, Angi, Erie Metal Roofs.',
        disclaimer: 'Quotes are provided by independent local contractors. Pricing and availability vary by area.' },
      debt: { label: 'Debt Relief', color: '#2b8a3e',
        brief: 'US unsecured debt relief: settlement vs consolidation, no upfront fees, credit impact, eligibility, timelines. Advertisers like National Debt Relief, Freedom Debt Relief, Achieve.',
        disclaimer: 'Debt relief programs are not available in all states; results vary; enrollment may affect credit. Not legal or financial advice.' }
    }
  },
  latam: {
    label: 'South America', dir: 'ltr', currency: 'local',
    locales: [{ code: 'es-419', name: 'Latin American Spanish' }, { code: 'pt-BR', name: 'Brazilian Portuguese' }],
    verticals: {
      solar: { label: 'Solar', color: '#f59f00',
        brief: 'Residential rooftop solar panels for homeowners in South America: cutting the electricity bill, financing/installments, government incentives, free quotes. Synthetic local installer advertisers.',
        disclaimer: 'Savings depend on consumption, roof and local tariffs. Quotes from independent installers. Demo content.' },
      credito: { label: 'Credit', color: '#1971c2',
        brief: 'Personal credit / debt consolidation for consumers in South America: lower monthly payments, single installment, eligibility check without affecting score. Synthetic local lender advertisers.',
        disclaimer: 'Subject to credit approval; terms vary by provider and country. Not financial advice. Demo content.' },
      ingles: { label: 'English Courses', color: '#7048e8',
        brief: 'Online English courses for adults in South America: career advancement, conversational fluency, free trial lesson, flexible plans. Synthetic ed-tech advertisers.',
        disclaimer: 'Results vary by effort and plan. Demo content.' }
    }
  },
  eu: {
    label: 'Europe', dir: 'ltr', currency: 'EUR',
    locales: [{ code: 'en-GB', name: 'British English' }, { code: 'de-DE', name: 'German' }, { code: 'fr-FR', name: 'French' }],
    verticals: {
      solar: { label: 'Solar & Heat Pumps', color: '#f59f00',
        brief: 'Home solar panels and heat pumps for European homeowners: energy-bill savings, government grants/subsidies, financing, free home assessment. Synthetic EU installer advertisers.',
        disclaimer: 'Savings and grant eligibility vary by country and household. Quotes from independent installers. Demo content.' },
      ev: { label: 'EV Leasing', color: '#0ca678',
        brief: 'Electric-vehicle leasing for Europe: low monthly lease, government EV incentives, all-inclusive deals, instant quote. Synthetic leasing advertisers.',
        disclaimer: 'Offers subject to status and country. Demo content.' },
      insurance: { label: 'Insurance', color: '#4263eb',
        brief: 'Home and auto insurance comparison for Europe: switch and save, compare top insurers in minutes, free quote. Synthetic comparison-site advertisers.',
        disclaimer: 'Savings vary by profile and country. Demo content.' }
    }
  },
  mena: {
    label: 'Middle East', dir: 'rtl', currency: 'AED',
    locales: [{ code: 'ar', name: 'Arabic' }, { code: 'en-AE', name: 'English' }],
    verticals: {
      realestate: { label: 'Property Investment', color: '#c2255c',
        brief: 'Off-plan and ready property investment in the Gulf (e.g. Dubai): flexible payment plans, high rental yields, residency-linked options, free consultation. Synthetic developer/broker advertisers.',
        disclaimer: 'Property values can go down as well as up. Not investment advice. Demo content.' },
      health: { label: 'Private Health', color: '#1098ad',
        brief: 'Private health insurance for residents and expats in the Gulf: family cover, compare plans, fast approval, free quote. Synthetic insurer advertisers.',
        disclaimer: 'Cover and eligibility vary by plan and emirate/country. Demo content.' },
      gold: { label: 'Gold Savings', color: '#e8950c',
        brief: 'Gold savings/investment plans in the Middle East: buy and store gold, monthly savings plans, hedge against inflation. Synthetic advertisers.',
        disclaimer: 'Gold prices fluctuate; capital at risk. Not investment advice. Demo content.' }
    }
  },
  apac: {
    label: 'Asia-Pacific', dir: 'ltr', currency: 'local',
    locales: [{ code: 'en-SG', name: 'English' }, { code: 'ja-JP', name: 'Japanese' }, { code: 'hi-IN', name: 'Hindi' }],
    verticals: {
      life: { label: 'Life Insurance', color: '#5f3dc4',
        brief: 'Life and term insurance across Asia-Pacific: affordable cover for families, compare plans, instant online quote, tax benefits where applicable. Synthetic insurer advertisers.',
        disclaimer: 'Cover and tax treatment vary by country and plan. Demo content.' },
      tutoring: { label: 'Tutoring', color: '#1c7ed6',
        brief: 'Online tutoring and exam prep across Asia-Pacific: top scores, expert tutors, free trial class, flexible schedules. Synthetic ed-tech advertisers.',
        disclaimer: 'Results vary by student. Demo content.' },
      travel: { label: 'Travel Deals', color: '#0c8599',
        brief: 'Discounted travel and flight/hotel deals across Asia-Pacific: limited-time fares, bundle and save, flexible booking. Synthetic OTA advertisers.',
        disclaimer: 'Prices and availability change. Demo content.' }
    }
  }
};

function localeName(region, locale) {
  const r = REGIONS[region]; if (!r) return 'English';
  const l = (r.locales || []).find(x => x.code === locale);
  return l ? l.name : (r.locales[0] ? r.locales[0].name : 'English');
}
function vertical(region, vkey) {
  const r = REGIONS[region]; if (!r) return null;
  return r.verticals[vkey] || null;
}

/* ---------------- model callers ---------------- */
async function callClaude(system, userText, history) {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) throw new Error('Missing ANTHROPIC_API_KEY');
  const model = process.env.CLAUDE_MODEL || 'claude-sonnet-4-6';
  const messages = [];
  for (const h of history || []) messages.push({ role: h.role, content: h.content });
  messages.push({ role: 'user', content: userText });
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01' },
    body: JSON.stringify({ model, max_tokens: 1500, system, messages })
  });
  if (!res.ok) throw new Error(`Anthropic ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return (data.content || []).map(b => b.text || '').join('');
}
async function callGemini(system, userText, history) {
  const key = process.env.GEMINI_API_KEY;
  if (!key) throw new Error('Missing GEMINI_API_KEY');
  const model = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
  const contents = [];
  for (const h of history || []) contents.push({ role: h.role === 'assistant' ? 'model' : 'user', parts: [{ text: h.content }] });
  contents.push({ role: 'user', parts: [{ text: userText }] });
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`;
  const res = await fetch(url, {
    method: 'POST', headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ systemInstruction: { parts: [{ text: system }] }, contents, generationConfig: { temperature: 0.8, responseMimeType: 'application/json' } })
  });
  if (!res.ok) throw new Error(`Gemini ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const parts = data?.candidates?.[0]?.content?.parts || [];
  return parts.map(p => p.text || '').join('');
}
async function callLLM(system, userText, history) {
  const provider = (process.env.PROVIDER || 'claude').toLowerCase();
  return provider === 'gemini' ? callGemini(system, userText, history) : callClaude(system, userText, history);
}
function parseJSON(raw) {
  if (!raw) throw new Error('Empty model response');
  let s = raw.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '');
  const a = s.search(/[\[{]/); const b = Math.max(s.lastIndexOf(']'), s.lastIndexOf('}'));
  if (a !== -1 && b !== -1) s = s.slice(a, b + 1);
  return JSON.parse(s);
}

/* ---------------- prompts ---------------- */
function hooksPrompt(v, lang, disclaimer) {
  return `You write high-CTR Facebook ad hooks for a lead-generation campaign. DEMO use; advertisers are synthetic.
Vertical: ${v.brief}
Write EVERYTHING in ${lang}.

Produce 10 DISTINCT, punchy, aggressive-but-not-misleading ad hooks a person would click — use angles like cost/price, free/$0, eligibility ("do you qualify?"), savings amount, speed, curiosity ("most people don't know"), social proof, and 2026 timeliness. Vary the angles. Keep each compliant and honestly hedged (no false guarantees). ${disclaimer}

Return STRICT JSON: an array of exactly 10 objects, each:
{"hook":"the ad text (1-2 sentences, in ${lang})","head":"short image-overlay headline (in ${lang}, <=6 words)","adv":"plausible synthetic advertiser name","url":"www.display-url.com","cta":"button text (in ${lang}, 2-3 words)"}
Output only the JSON array.`;
}
function openerPrompt(v, lang, disclaimer) {
  return `You are a friendly, genuinely helpful assistant embedded in a lead-gen chat. Answer in ${lang}, naturally and usefully first (2-4 short sentences) — like a knowledgeable friend, not a salesperson.
Topic: ${v.brief}

Only when a high-intent commercial phrase fits naturally, wrap it as [[id|the exact visible phrase in ${lang}]] (id = short lowercase ascii slug). Use 0-2 markers; zero is fine. Never force one.
For each id used, give one realistic, compelling synthetic sponsored ad. Provide 4-6 natural follow-up questions in ${lang}. Include a soft honest disclaimer where relevant (${disclaimer}).

Return STRICT JSON only:
{"answer":"... in ${lang} with optional [[id|phrase]] markers","ads":{"<id>":{"adv":"","disp":"www.url.com/x","url":"https://...","head":"","desc":"","cta":"","sitelinks":["",""]}},"suggest":["",""]}
Output only the JSON object.`;
}

/* ---------------- Upstash (cache + counters + leads) ---------------- */
const MIN_COUNT = 3, MAX_SET = 200;
function redisUrl() { return process.env.KV_REST_API_URL || process.env.UPSTASH_REDIS_REST_URL || ''; }
function redisToken() { return process.env.KV_REST_API_TOKEN || process.env.UPSTASH_REDIS_REST_TOKEN || ''; }
function redisOn() { return !!(redisUrl() && redisToken()); }
async function redis(cmd) {
  const url = redisUrl(), token = redisToken(); if (!url || !token) return null;
  const res = await fetch(url, { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: JSON.stringify(cmd) });
  if (!res.ok) throw new Error('redis ' + res.status);
  return (await res.json()).result;
}
async function cacheGet(key) { try { if (!redisOn()) return null; const v = await redis(['GET', key]); return v ? JSON.parse(v) : null; } catch { return null; } }
async function cacheSet(key, val) { try { if (redisOn()) await redis(['SET', key, JSON.stringify(val)]); } catch {} }
function hashStr(s) { let h = 0; s = String(s); for (let i = 0; i < s.length; i++) { h = (h * 31 + s.charCodeAt(i)) | 0; } return (h >>> 0).toString(36); }

/* ---------------- generation (cached) ---------------- */
export async function getLineup(region, vkey, locale) {
  const v = vertical(region, vkey); if (!v) throw new Error('Unknown vertical');
  const lang = localeName(region, locale);
  const key = `hooks:${locale}:${region}:${vkey}`;
  const cached = await cacheGet(key); if (cached) return cached;
  const raw = await callLLM(hooksPrompt(v, lang, v.disclaimer), 'Generate the 10 hooks now.');
  let arr = parseJSON(raw); if (!Array.isArray(arr)) arr = arr.hooks || [];
  arr = arr.filter(x => x && x.hook).slice(0, 10).map((x, i) => ({ id: 'v' + (i + 1), hook: String(x.hook), head: String(x.head || x.hook).slice(0, 60), adv: String(x.adv || 'Sponsored'), url: String(x.url || 'www.example.com'), cta: String(x.cta || 'Learn More') }));
  if (arr.length) await cacheSet(key, arr);
  return arr;
}
export async function getOpener(region, vkey, locale, hook) {
  const v = vertical(region, vkey); if (!v) throw new Error('Unknown vertical');
  const lang = localeName(region, locale);
  const key = `opener:${locale}:${region}:${vkey}:${hashStr(hook)}`;
  const cached = await cacheGet(key); if (cached) return cached;
  const raw = await callLLM(openerPrompt(v, lang, v.disclaimer), `The Facebook ad said: "${hook}". Open the conversation by helpfully answering what it implies (respond to the FULL ad including any "$0"/free/price detail).`);
  const out = normalizeReply(parseJSON(raw));
  await cacheSet(key, out);
  return out;
}

function normalizeReply(obj) {
  if (typeof obj.answer !== 'string') throw new Error('No answer');
  obj.ads = obj.ads && typeof obj.ads === 'object' ? obj.ads : {};
  obj.suggest = Array.isArray(obj.suggest) ? obj.suggest : [];
  return obj;
}

/* ---------------- follow-up chat (localized) ---------------- */
function canonical(s) { s = String(s || '').toLowerCase().replace(/\s+/g, ' ').trim().replace(/[.?!]+$/, ''); return s ? s[0].toUpperCase() + s.slice(1) : s; }
const BANNED = /\b(fuck|shit|bitch|cunt|nigger|faggot|kill yourself|kys)\b/i;
function isLoggable(s) { return s.length >= 8 && s.length <= 120 && /[\p{L}]/u.test(s) && !/[\w.+-]+@[\w-]+\.[a-z]{2,}/i.test(s) && !/(?:\+?\d[\s().-]?){7,}/.test(s) && !/\b\d{5,}\b/.test(s) && !BANNED.test(s); }

async function logQuestion(scope, q) {
  try { if (!redisOn()) return; const c = canonical(q); if (!isLoggable(c)) return; const key = `paa:${scope}`; await redis(['ZINCRBY', key, '1', c]); await redis(['ZREMRANGEBYRANK', key, '0', String(-(MAX_SET + 1))]); } catch {}
}
async function blendSuggestions(scope, currentQ, modelSuggest) {
  const cq = canonical(currentQ); const model = (modelSuggest || []).filter(Boolean).slice(0, 3); const seen = new Set(model.map(canonical)); seen.add(cq); const popular = [];
  try { if (redisOn()) { const raw = await redis(['ZREVRANGE', `paa:${scope}`, '0', '11', 'WITHSCORES']); if (Array.isArray(raw)) { for (let i = 0; i < raw.length; i += 2) { const m = raw[i], sc = Number(raw[i + 1]); const c = canonical(m); if (sc >= MIN_COUNT && !seen.has(c)) { seen.add(c); popular.push(m); } if (popular.length >= 3) break; } } } } catch {}
  const blended = [...model, ...popular].slice(0, 6); return blended.length ? blended : (modelSuggest || []);
}

export async function ask(region, vkey, locale, question, history) {
  const v = vertical(region, vkey); if (!v) throw new Error('Unknown vertical');
  const lang = localeName(region, locale);
  const raw = await callLLM(openerPrompt(v, lang, v.disclaimer), question, history);
  const out = normalizeReply(parseJSON(raw));
  const scope = `${locale}:${region}:${vkey}`;
  await logQuestion(scope, question);
  out.suggest = await blendSuggestions(scope, question, out.suggest);
  return out;
}

/* ---------------- public metadata for the UI ---------------- */
export function publicRegions() {
  const out = {};
  for (const [rk, r] of Object.entries(REGIONS)) {
    out[rk] = { label: r.label, dir: r.dir, currency: r.currency, locales: r.locales,
      verticals: Object.fromEntries(Object.entries(r.verticals).map(([vk, v]) => [vk, { label: v.label, color: v.color, disclaimer: v.disclaimer }])) };
  }
  return out;
}

/* ---------------- leads + events ---------------- */
function validEmail(raw) { const e = String(raw || '').trim().toLowerCase(); return e.length <= 120 && /^[^\s@]+@[^\s@]+\.[a-z]{2,}$/.test(e) ? e : null; }
export async function storeLead(scope, email) {
  const e = validEmail(email); if (!e) throw new Error('Please enter a valid email address.');
  const k = String(scope || 'all').replace(/[^a-z0-9:_-]/gi, '').slice(0, 60);
  if (redisOn()) { try { await redis(['SADD', `leads:${k}`, e]); await redis(['SADD', 'leads:all', e]); await redis(['HINCRBY', `stats:${k}`, 'email_optin', '1']); } catch {} }
  return { ok: true };
}
export async function track(scope, metric) {
  try { const k = String(scope || 'all').replace(/[^a-z0-9:_-]/gi, '').slice(0, 60); const m = String(metric || ''); if (redisOn() && /^[a-z0-9:_-]{1,40}$/i.test(m)) await redis(['HINCRBY', `stats:${k}`, m, '1']); } catch {}
  return { ok: true };
}


export default async function handler(req, res) {
  if (req.method === 'GET') {
    // allow a quick GET for the regions metadata (handy + cacheable)
    if ((req.url || '').includes('/api/ask')) { res.status(200).json({ regions: publicRegions() }); return; }
  }
  if (req.method !== 'POST') { res.status(405).json({ error: 'Method not allowed' }); return; }
  try {
    let body = req.body;
    if (typeof body === 'string') body = JSON.parse(body || '{}');
    if (!body || typeof body !== 'object') body = {};
    const action = body.action || 'ask';
    const { region, vertical, locale, hook, question, history, email, metric, scope } = body;

    if (action === 'regions') { res.status(200).json({ regions: publicRegions() }); return; }
    if (action === 'lineup') {
      if (!region || !vertical || !locale) { res.status(400).json({ error: 'region, vertical, locale required' }); return; }
      res.status(200).json({ variants: await getLineup(region, vertical, locale) }); return;
    }
    if (action === 'opener') {
      if (!region || !vertical || !locale || !hook) { res.status(400).json({ error: 'region, vertical, locale, hook required' }); return; }
      res.status(200).json(await getOpener(region, vertical, locale, String(hook).slice(0, 300))); return;
    }
    if (action === 'lead') { res.status(200).json(await storeLead(scope, email)); return; }
    if (action === 'event') { res.status(200).json(await track(scope, metric)); return; }

    // default: localized follow-up chat
    if (!region || !vertical || !locale || !question) { res.status(400).json({ error: 'region, vertical, locale, question required' }); return; }
    res.status(200).json(await ask(region, vertical, locale, String(question).slice(0, 500), history));
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
}
